fieldLayouts:
  090fd4a0-91d3-40e0-9d27-5914178cd059:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bb9973b9-245d-4108-94b1-2707a87dadd9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6d2b17c2-da19-4596-a43e-b75e912fdeeb # project Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0055dcaa-4ffb-4ec4-b939-19ee5fce6e5e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0c1f3290-52fa-4343-ac91-be725216b4f4 # project Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2145d52-1a52-4642-a673-6092966c77bb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 34a7cf96-d750-45d0-8d5a-0589cff7d1c0
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: c98002e6-2975-4bbb-9025-9ae3e4f77f83 # projects
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
