fieldLayouts:
  1e032164-1a35-449e-b5fe-c19c73be8c76:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: d65993a7-7d9b-4711-be03-cb2d74f81ec5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fdfb0ff2-6d1a-4110-b6a0-4e703874abf8
        userCondition: null
fs: allimages
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
