columnSuffix: esifchwp
contentColumnType: integer(10)
fieldGroup: 7363904e-a5d1-4ef0-b5cf-ad598c922a68 # Common
handle: footerPhonenumber
instructions: null
name: 'Footer Phonenumber'
searchable: false
settings:
  decimals: 0
  defaultValue: 254
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
