columnSuffix: vwgmoisn
contentColumnType: text
fieldGroup: 6dd1fbd2-7a00-4dd0-869f-c678899cf8ee # Home
handle: heroSubtitle
instructions: null
name: 'Hero Subtitle'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
