columnSuffix: zpfhmtvl
contentColumnType: text
fieldGroup: 49c08815-608a-4b26-a9ab-dda7724f7b62 # AboutUs 
handle: missionText
instructions: null
name: 'mission Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
