columnSuffix: jwywtjki
contentColumnType: text
fieldGroup: 7363904e-a5d1-4ef0-b5cf-ad598c922a68 # Common
handle: preloaderTitle
instructions: null
name: 'preloader Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
