columnSuffix: axmiyjih
contentColumnType: string
fieldGroup: c4293c92-f128-434c-a51f-4c3ea58bb4ff # services
handle: services
instructions: null
name: Services
searchable: false
settings:
  contentTable: '{{%matrixcontent_services}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
