defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  95fb19d8-e7fb-43bb-8322-0eda144557a3: # http://site.test
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
