defaultPlacement: end
enableVersioning: true
handle: services
name: services
propagationMethod: all
siteSettings:
  95fb19d8-e7fb-43bb-8322-0eda144557a3: # http://site.test
    enabledByDefault: true
    hasUrls: true
    template: services\entry.twig
    uriFormat: 'services/{slug}'
type: channel
